# Generated by Django 5.2 on 2025-04-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_date', models.DateTimeField(auto_now_add=True, verbose_name='workout date')),
                ('wo_type', models.CharField(max_length=50, verbose_name='workout type')),
                ('wo_intensity', models.IntegerField(verbose_name='workout intensity')),
                ('wo_set_qty', models.IntegerField(verbose_name='workout set quantity')),
                ('wo_qty_of_set', models.IntegerField(verbose_name='workout quantity of set')),
                ('wo_duration', models.IntegerField(verbose_name='workout duration')),
            ],
        ),
    ]
